using System;
using System.Collections.Generic;

#nullable disable

namespace Barunn.MobileInvitation.Dac.Models.BarShop
{
    public partial class CARD
    {
        public int CARD_SEQ { get; set; }
        public short? CARD_GROUP { get; set; }
        public string CARD_CATE { get; set; }
        public int? CARD_CATEGORY_SEQ { get; set; }
        public byte? CARD_KIND { get; set; }
        public string CARD_DIV { get; set; }
        public string CARD_NAME { get; set; }
        public string CARD_CODE { get; set; }
        public string ERP_CODE { get; set; }
        public string NEW_CODE { get; set; }
        public string CARD_KEYWORD { get; set; }
        public string CARD_KEYWORD_SRC { get; set; }
        public int CARD_PRICE_CUSTOMER { get; set; }
        public string DISPLAY_YES_OR_NO { get; set; }
        public string JUMUN_YES_OR_NO { get; set; }
        public string B2B_YES_OR_NO { get; set; }
        public string RECOMEND_YES_OR_NO { get; set; }
        public string CARD_FPrint { get; set; }
        public string CARD_IMG_S { get; set; }
        public string CARD_IMG_XS { get; set; }
        public string CARD_IMG_MS { get; set; }
        public string CARD_IMG_M1 { get; set; }
        public string CARD_IMG_M2 { get; set; }
        public string CARD_IMG_M3 { get; set; }
        public string CARD_IMG_M4 { get; set; }
        public string CARD_IMG_M5 { get; set; }
        public string CARD_IMG_M6 { get; set; }
        public string CARD_IMG_B1 { get; set; }
        public string CARD_IMG_B2 { get; set; }
        public string CARD_IMG_B4 { get; set; }
        public string CARD_IMG_B5 { get; set; }
        public string CARD_IMG_B6 { get; set; }
        public string CARD_IMG_B7 { get; set; }
        public string CARD_IMG_B8 { get; set; }
        public string CARD_IMG_B9 { get; set; }
        public string CARD_IMG_B10 { get; set; }
        public string CARD_IMG_B11 { get; set; }
        public string CARD_IMG_B12 { get; set; }
        public string CARD_IMG_B13 { get; set; }
        public string CARD_IMG_B14 { get; set; }
        public string CARD_IMG_B15 { get; set; }
        public string CARD_IMG_ORDER1 { get; set; }
        public string CARD_IMG_ORDER2 { get; set; }
        public string CARD_PAPER { get; set; }
        public string CARD_SIZE { get; set; }
        public string CARD_OSI { get; set; }
        public short? COMPANY { get; set; }
        public int PRINT_SIZE { get; set; }
        public short? PRODUCE_YEAR { get; set; }
        public string PRODUCE_PLACE { get; set; }
        public int? set_seq { get; set; }
        public int? SALES_RANKING { get; set; }
        public string CARD_DESCRIPTION { get; set; }
        public DateTime? REGIST_DATE { get; set; }
        public DateTime? LAST_UPDATE { get; set; }
        public string CARD_IMG_B3 { get; set; }
        public string CARD_ENVELOPE { get; set; }
        public int? CARD_PRICE { get; set; }
        public double? CARD_SRC_PRICE { get; set; }
        public double? CARD_BRANCH_PRICE { get; set; }
        public double? CARD_ONLINE_BRANCH_PRICE { get; set; }
        public double? CARD_B2B_PRICE { get; set; }
        public double? CARD_DISCOUNT_RATE { get; set; }
        public string CARD_IMG_D { get; set; }
        public string DISRATE_TYPE { get; set; }
        public string BEST_YES_OR_NO { get; set; }
        public string BEST_STR { get; set; }
        public string online_yes_or_no { get; set; }
        public string NEW_YES_OR_NO { get; set; }
        public string IsEnvInsert { get; set; }
        public string IsSBaesong { get; set; }
        public string IsFPrint { get; set; }
        public string ISHAVE { get; set; }
        public int? ISHAVE_NUM { get; set; }
        public string ISInPaper { get; set; }
        public string IsHandMade { get; set; }
        public string IsFreehandmade { get; set; }
        public string IsFreeEmbo { get; set; }
        public string IsEmbo { get; set; }
        public string IsInitial { get; set; }
        public string IsOsiGaro { get; set; }
        public string IsSilk { get; set; }
        public string IsGold { get; set; }
        public string IsRibon { get; set; }
        public string IsFlower { get; set; }
        public string IsHeart { get; set; }
        public string IsWonang { get; set; }
        public string IsYu { get; set; }
        public string IsHanji { get; set; }
        public string IsSelfEdit { get; set; }
        public string IsColorInpaper { get; set; }
        public string IsSpecialThank { get; set; }
        public string IsSample { get; set; }
        public string IsOffDisplay { get; set; }
        public string IsOffBest { get; set; }
        public string IsOffDDisplay { get; set; }
        public string IsOBDisplay { get; set; }
        public string Env_code { get; set; }
        public string cont_code { get; set; }
        public string acc_code { get; set; }
        public string env_code_o { get; set; }
        public string cont_code_o { get; set; }
        public int? acc_seq { get; set; }
        public int? env_seq { get; set; }
        public int? cont_seq { get; set; }
        public int? acc_seq2 { get; set; }
        public int? place_seq { get; set; }
        public int? cont_seq_b2b { get; set; }
        public int? env_seq_b2b { get; set; }
        public string Is100 { get; set; }
        public string Is1001 { get; set; }
        public string Is1002 { get; set; }
        public string Is1003 { get; set; }
        public string Is1004 { get; set; }
        public string Is1005 { get; set; }
        public string IsUsrimg1 { get; set; }
        public string IsUsrimg2 { get; set; }
        public string IsUsrimg3 { get; set; }
        public string IsUsrComment { get; set; }
        public string Is1009 { get; set; }
        public string Is200 { get; set; }
        public string Is400 { get; set; }
        public string Is300 { get; set; }
        public string Is3001 { get; set; }
        public string Is500 { get; set; }
        public string ADMIN_ID { get; set; }
        public string ADMIN_MEMO { get; set; }
        public double? CARD_MARKET_PRICE { get; set; }
        public string isModern { get; set; }
        public string isSweet { get; set; }
        public string isRomantic { get; set; }
        public string isStylish { get; set; }
        public string isTrendy { get; set; }
        public string isElegant { get; set; }
        public string isTie { get; set; }
        public string isPearl { get; set; }
        public string isPress { get; set; }
        public string isWinitial { get; set; }
        public string isHologram { get; set; }
        public string isButterfly { get; set; }
        public short? BestRangking { get; set; }
        public string Card_Shape { get; set; }
        public string ReInputDate { get; set; }
        public string Is1006 { get; set; }
        public string isColorPrt { get; set; }
    }
}
